package com.gi2.footwork.ui.theme

import androidx.compose.ui.graphics.Brush
import androidx.compose.ui.graphics.Color

// brand color
val primaryFixed = Color(0xFF52B040)
val onPrimaryFixed = Color(0xFFFAFAFA)

val primaryLight = Color(0xFF076E00)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFF5EBD4B)
val onPrimaryContainerLight = Color(0xFF012400)
val secondaryLight = Color(0xFF426738)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFFC8F3B7)
val onSecondaryContainerLight = Color(0xFF2F5326)
val tertiaryLight = Color(0xFF006783)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFF29B6E2)
val onTertiaryContainerLight = Color(0xFF00212D)
val errorLight = Color(0xFFBA1A1A)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFFFDAD6)
val onErrorContainerLight = Color(0xFF410002)
val backgroundLight = Color(0xFFF6FBEE)
val onBackgroundLight = Color(0xFF171D15)
val surfaceLight = Color(0xFFF6FBEE)
val onSurfaceLight = Color(0xFF171D15)
val surfaceVariantLight = Color(0xFFDBE6D2)
val onSurfaceVariantLight = Color(0xFF404A3B)
val outlineLight = Color(0xFF707A69)
val outlineVariantLight = Color(0xFFBFCAB6)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF2C3229)
val inverseOnSurfaceLight = Color(0xFFEDF3E5)
val inversePrimaryLight = Color(0xFF7CDC66)
val surfaceDimLight = Color(0xFFD6DCCF)
val surfaceBrightLight = Color(0xFFF6FBEE)
val surfaceContainerLowestLight = Color(0xFFFFFFFF)
val surfaceContainerLowLight = Color(0xFFF0F6E8)
val surfaceContainerLight = Color(0xFFEAF0E2)
val surfaceContainerHighLight = Color(0xFFE4EADD)
val surfaceContainerHighestLight = Color(0xFFDFE5D7)

//val primaryLightMediumContrast = Color(0xFF044F00)
//val onPrimaryLightMediumContrast = Color(0xFFFFFFFF)
//val primaryContainerLightMediumContrast = Color(0xFF278619)
//val onPrimaryContainerLightMediumContrast = Color(0xFFFFFFFF)
//val secondaryLightMediumContrast = Color(0xFF274B1F)
//val onSecondaryLightMediumContrast = Color(0xFFFFFFFF)
//val secondaryContainerLightMediumContrast = Color(0xFF587E4C)
//val onSecondaryContainerLightMediumContrast = Color(0xFFFFFFFF)
//val tertiaryLightMediumContrast = Color(0xFF00495E)
//val onTertiaryLightMediumContrast = Color(0xFFFFFFFF)
//val tertiaryContainerLightMediumContrast = Color(0xFF007EA0)
//val onTertiaryContainerLightMediumContrast = Color(0xFFFFFFFF)
//val errorLightMediumContrast = Color(0xFF8C0009)
//val onErrorLightMediumContrast = Color(0xFFFFFFFF)
//val errorContainerLightMediumContrast = Color(0xFFDA342E)
//val onErrorContainerLightMediumContrast = Color(0xFFFFFFFF)
//val backgroundLightMediumContrast = Color(0xFFF6FBEE)
//val onBackgroundLightMediumContrast = Color(0xFF171D15)
//val surfaceLightMediumContrast = Color(0xFFF6FBEE)
//val onSurfaceLightMediumContrast = Color(0xFF171D15)
//val surfaceVariantLightMediumContrast = Color(0xFFDBE6D2)
//val onSurfaceVariantLightMediumContrast = Color(0xFF3C4637)
//val outlineLightMediumContrast = Color(0xFF586252)
//val outlineVariantLightMediumContrast = Color(0xFF737E6D)
//val scrimLightMediumContrast = Color(0xFF000000)
//val inverseSurfaceLightMediumContrast = Color(0xFF2C3229)
//val inverseOnSurfaceLightMediumContrast = Color(0xFFEDF3E5)
//val inversePrimaryLightMediumContrast = Color(0xFF7CDC66)
//val surfaceDimLightMediumContrast = Color(0xFFD6DCCF)
//val surfaceBrightLightMediumContrast = Color(0xFFF6FBEE)
//val surfaceContainerLowestLightMediumContrast = Color(0xFFFFFFFF)
//val surfaceContainerLowLightMediumContrast = Color(0xFFF0F6E8)
//val surfaceContainerLightMediumContrast = Color(0xFFEAF0E2)
//val surfaceContainerHighLightMediumContrast = Color(0xFFE4EADD)
//val surfaceContainerHighestLightMediumContrast = Color(0xFFDFE5D7)

//val primaryLightHighContrast = Color(0xFF012900)
//val onPrimaryLightHighContrast = Color(0xFFFFFFFF)
//val primaryContainerLightHighContrast = Color(0xFF044F00)
//val onPrimaryContainerLightHighContrast = Color(0xFFFFFFFF)
//val secondaryLightHighContrast = Color(0xFF052902)
//val onSecondaryLightHighContrast = Color(0xFFFFFFFF)
//val secondaryContainerLightHighContrast = Color(0xFF274B1F)
//val onSecondaryContainerLightHighContrast = Color(0xFFFFFFFF)
//val tertiaryLightHighContrast = Color(0xFF002632)
//val onTertiaryLightHighContrast = Color(0xFFFFFFFF)
//val tertiaryContainerLightHighContrast = Color(0xFF00495E)
//val onTertiaryContainerLightHighContrast = Color(0xFFFFFFFF)
//val errorLightHighContrast = Color(0xFF4E0002)
//val onErrorLightHighContrast = Color(0xFFFFFFFF)
//val errorContainerLightHighContrast = Color(0xFF8C0009)
//val onErrorContainerLightHighContrast = Color(0xFFFFFFFF)
//val backgroundLightHighContrast = Color(0xFFF6FBEE)
//val onBackgroundLightHighContrast = Color(0xFF171D15)
//val surfaceLightHighContrast = Color(0xFFF6FBEE)
//val onSurfaceLightHighContrast = Color(0xFF000000)
//val surfaceVariantLightHighContrast = Color(0xFFDBE6D2)
//val onSurfaceVariantLightHighContrast = Color(0xFF1D2619)
//val outlineLightHighContrast = Color(0xFF3C4637)
//val outlineVariantLightHighContrast = Color(0xFF3C4637)
//val scrimLightHighContrast = Color(0xFF000000)
//val inverseSurfaceLightHighContrast = Color(0xFF2C3229)
//val inverseOnSurfaceLightHighContrast = Color(0xFFFFFFFF)
//val inversePrimaryLightHighContrast = Color(0xFFB5FF9E)
//val surfaceDimLightHighContrast = Color(0xFFD6DCCF)
//val surfaceBrightLightHighContrast = Color(0xFFF6FBEE)
//val surfaceContainerLowestLightHighContrast = Color(0xFFFFFFFF)
//val surfaceContainerLowLightHighContrast = Color(0xFFF0F6E8)
//val surfaceContainerLightHighContrast = Color(0xFFEAF0E2)
//val surfaceContainerHighLightHighContrast = Color(0xFFE4EADD)
//val surfaceContainerHighestLightHighContrast = Color(0xFFDFE5D7)

val primaryDark = Color(0xFF7CDC66)
val onPrimaryDark = Color(0xFF023900)
val primaryContainerDark = Color(0xFF49A738)
val onPrimaryContainerDark = Color(0xFF000000)
val secondaryDark = Color(0xFFA8D298)
val onSecondaryDark = Color(0xFF15380E)
val secondaryContainerDark = Color(0xFF22451A)
val onSecondaryContainerDark = Color(0xFFB2DCA2)
val tertiaryDark = Color(0xFF61D4FF)
val onTertiaryDark = Color(0xFF003545)
val tertiaryContainerDark = Color(0xFF00A0CA)
val onTertiaryContainerDark = Color(0xFF000000)
val errorDark = Color(0xFFFFB4AB)
val onErrorDark = Color(0xFF690005)
val errorContainerDark = Color(0xFF93000A)
val onErrorContainerDark = Color(0xFFFFDAD6)
val backgroundDark = Color(0xFF0F150D)
val onBackgroundDark = Color(0xFFDFE5D7)
val surfaceDark = Color(0xFF0F150D)
val onSurfaceDark = Color(0xFFDFE5D7)
val surfaceVariantDark = Color(0xFF404A3B)
val onSurfaceVariantDark = Color(0xFFBFCAB6)
val outlineDark = Color(0xFF899482)
val outlineVariantDark = Color(0xFF404A3B)
val scrimDark = Color(0xFF000000)
val inverseSurfaceDark = Color(0xFFDFE5D7)
val inverseOnSurfaceDark = Color(0xFF2C3229)
val inversePrimaryDark = Color(0xFF076E00)
val surfaceDimDark = Color(0xFF0F150D)
val surfaceBrightDark = Color(0xFF353B32)
val surfaceContainerLowestDark = Color(0xFF0A1008)
val surfaceContainerLowDark = Color(0xFF171D15)
val surfaceContainerDark = Color(0xFF1B2119)
val surfaceContainerHighDark = Color(0xFF262C23)
val surfaceContainerHighestDark = Color(0xFF31362D)

//val primaryDarkMediumContrast = Color(0xFF80E16A)
//val onPrimaryDarkMediumContrast = Color(0xFF011C00)
//val primaryContainerDarkMediumContrast = Color(0xFF49A738)
//val onPrimaryContainerDarkMediumContrast = Color(0xFF000000)
//val secondaryDarkMediumContrast = Color(0xFFACD69C)
//val onSecondaryDarkMediumContrast = Color(0xFF011C00)
//val secondaryContainerDarkMediumContrast = Color(0xFF739B66)
//val onSecondaryContainerDarkMediumContrast = Color(0xFF000000)
//val tertiaryDarkMediumContrast = Color(0xFF73D7FF)
//val onTertiaryDarkMediumContrast = Color(0xFF001922)
//val tertiaryContainerDarkMediumContrast = Color(0xFF00A0CA)
//val onTertiaryContainerDarkMediumContrast = Color(0xFF000000)
//val errorDarkMediumContrast = Color(0xFFFFBAB1)
//val onErrorDarkMediumContrast = Color(0xFF370001)
//val errorContainerDarkMediumContrast = Color(0xFFFF5449)
//val onErrorContainerDarkMediumContrast = Color(0xFF000000)
//val backgroundDarkMediumContrast = Color(0xFF0F150D)
//val onBackgroundDarkMediumContrast = Color(0xFFDFE5D7)
//val surfaceDarkMediumContrast = Color(0xFF0F150D)
//val onSurfaceDarkMediumContrast = Color(0xFFF7FDEF)
//val surfaceVariantDarkMediumContrast = Color(0xFF404A3B)
//val onSurfaceVariantDarkMediumContrast = Color(0xFFC3CEBB)
//val outlineDarkMediumContrast = Color(0xFF9BA694)
//val outlineVariantDarkMediumContrast = Color(0xFF7C8675)
//val scrimDarkMediumContrast = Color(0xFF000000)
//val inverseSurfaceDarkMediumContrast = Color(0xFFDFE5D7)
//val inverseOnSurfaceDarkMediumContrast = Color(0xFF262C23)
//val inversePrimaryDarkMediumContrast = Color(0xFF045500)
//val surfaceDimDarkMediumContrast = Color(0xFF0F150D)
//val surfaceBrightDarkMediumContrast = Color(0xFF353B32)
//val surfaceContainerLowestDarkMediumContrast = Color(0xFF0A1008)
//val surfaceContainerLowDarkMediumContrast = Color(0xFF171D15)
//val surfaceContainerDarkMediumContrast = Color(0xFF1B2119)
//val surfaceContainerHighDarkMediumContrast = Color(0xFF262C23)
//val surfaceContainerHighestDarkMediumContrast = Color(0xFF31362D)

//val primaryDarkHighContrast = Color(0xFFF2FFE7)
//val onPrimaryDarkHighContrast = Color(0xFF000000)
//val primaryContainerDarkHighContrast = Color(0xFF80E16A)
//val onPrimaryContainerDarkHighContrast = Color(0xFF000000)
//val secondaryDarkHighContrast = Color(0xFFF2FFE7)
//val onSecondaryDarkHighContrast = Color(0xFF000000)
//val secondaryContainerDarkHighContrast = Color(0xFFACD69C)
//val onSecondaryContainerDarkHighContrast = Color(0xFF000000)
//val tertiaryDarkHighContrast = Color(0xFFF6FBFF)
//val onTertiaryDarkHighContrast = Color(0xFF000000)
//val tertiaryContainerDarkHighContrast = Color(0xFF73D7FF)
//val onTertiaryContainerDarkHighContrast = Color(0xFF000000)
//val errorDarkHighContrast = Color(0xFFFFF9F9)
//val onErrorDarkHighContrast = Color(0xFF000000)
//val errorContainerDarkHighContrast = Color(0xFFFFBAB1)
//val onErrorContainerDarkHighContrast = Color(0xFF000000)
//val backgroundDarkHighContrast = Color(0xFF0F150D)
//val onBackgroundDarkHighContrast = Color(0xFFDFE5D7)
//val surfaceDarkHighContrast = Color(0xFF0F150D)
//val onSurfaceDarkHighContrast = Color(0xFFFFFFFF)
//val surfaceVariantDarkHighContrast = Color(0xFF404A3B)
//val onSurfaceVariantDarkHighContrast = Color(0xFFF3FEE9)
//val outlineDarkHighContrast = Color(0xFFC3CEBB)
//val outlineVariantDarkHighContrast = Color(0xFFC3CEBB)
//val scrimDarkHighContrast = Color(0xFF000000)
//val inverseSurfaceDarkHighContrast = Color(0xFFDFE5D7)
//val inverseOnSurfaceDarkHighContrast = Color(0xFF000000)
//val inversePrimaryDarkHighContrast = Color(0xFF023200)
//val surfaceDimDarkHighContrast = Color(0xFF0F150D)
//val surfaceBrightDarkHighContrast = Color(0xFF353B32)
//val surfaceContainerLowestDarkHighContrast = Color(0xFF0A1008)
//val surfaceContainerLowDarkHighContrast = Color(0xFF171D15)
//val surfaceContainerDarkHighContrast = Color(0xFF1B2119)
//val surfaceContainerHighDarkHighContrast = Color(0xFF262C23)
//val surfaceContainerHighestDarkHighContrast = Color(0xFF31362D)

val redVerticalGradient = Brush.verticalGradient(
  colors = listOf(
    Color(0xFFFF758E),
    Color(0xFFB22F47)
  ),
  startY = 0f, endY = 100f
)

val blueVerticalGradient = Brush.verticalGradient(
  colors = listOf(
    Color(0xFF5ECCFF),
    Color(0xFF2F80B2)
  ),
  startY = 0f, endY = 100f
)

val magentaVerticalGradient = Brush.verticalGradient(
  colors = listOf(
    Color(0xFFFF5ED1),
    Color(0xFFB22F84)
  )
)

val purpleVerticalGradient = Brush.verticalGradient(
  colors = listOf(
    Color(0xFFB675FF),
    Color(0xFF752FB2)
  )
)

val greenVerticalGradient = Brush.verticalGradient(
  listOf(
    Color(0xFF66FB82),
    Color(0xFF36B22F)
  )
)

val silverVerticalGradient = Brush.verticalGradient(
  colors = listOf(
    Color(0xFFD8D8D8),
    Color(0xFFA8A8A8)
  ),
  startY = 0f, endY = 100f
)

val homeSectionTitle = Color(0xFF404040)
val userGreetingSubText = Color(0xFFB8B8B8)
val statsProgressIndicator = Color(0xFFFFB20D)
val contributionProgressIndicatorTrack = Color(0xFF99DDA8)